name: Fork Core Repository

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Pull from Upstream
      run: |
        git remote add upstream https://github.com/example/test.git
        git fetch upstream

    - name: Merge
      run: |
        git checkout main
        git merge --no-edit upstream/main

    - name: Push to Origin
      run: |
        git push origin main
