name: Fork Core Repository

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ORG_NAME: PI-coffeeBreak

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Pull from Upstream
      run: |
        git remote add upstream https://github.com/example/test.git  # Replace with the actual upstream repo URL
        git fetch upstream

    - name: Check for changes and merge if any
      run: |
        git checkout main
        # Check if there are changes to merge
        if git rev-list HEAD...upstream/main --count | grep -q '[1-9]'; then
          echo "Changes detected, merging upstream/main into main..."
          git merge --no-edit upstream/main
        else
          echo "No changes to merge. The branches are already in sync."
        fi

    - name: Push to Fork (Origin)
      run: |
        git remote set-url origin https://$ORG_NAME:${{ secrets.PAT_TOKEN }}@github.com/$ORG_NAME/api-application-deployment.git
        git push origin main
